DROP TABLE BASKET;
DROP SEQUENCE BASKET_NO_SEQ;

CREATE SEQUENCE BASKET_NO_SEQ;

--장바구니
CREATE TABLE BASKET(
	BASKET_NO NUMBER(10) PRIMARY KEY,
	USER_NO NUMBER(20) NOT NULL,
	ITEM_NO NUMBER(20) NOT NULL,
	CONSTRAINT USER_FK FOREIGN KEY (USER_NO) REFERENCES USER_INFO(USER_NO),
	CONSTRAINT ITEM_FK FOREIGN KEY (ITEM_NO) REFERENCES ITEM(ITEM_NO)
);

SELECT * FROM BASKET;