DROP TABLE CATEGORY;
DROP SEQUENCE CATEGORY_NO_SEQ;


CREATE SEQUENCE CATEGORY_NO_SEQ;


CREATE TABLE CATEGORY(
	CATEGORY_NO NUMBER(2) PRIMARY KEY,
	CATE_NO NUMBER(2) NOT NULL,  
	PARENT_NO NUMBER(2),  --0아우터,1상의,2하의,3악세사리, parent_no가 없으면 null
	CATE_TITLE VARCHAR2(20) NOT NULL
);

INSERT INTO CATEGORY(CATEGORY_NO,CATE_NO,CATE_TITLE)
VALUES(CATEGORY_NO_SEQ.NEXTVAL, 0 ,'아우터');
INSERT INTO CATEGORY
VALUES(CATEGORY_NO_SEQ.NEXTVAL, 0, 0,'가디건');
INSERT INTO CATEGORY
VALUES(CATEGORY_NO_SEQ.NEXTVAL, 1,0,'자켓/점퍼');
INSERT INTO CATEGORY
VALUES(CATEGORY_NO_SEQ.NEXTVAL, 2,0,'코트');
INSERT INTO CATEGORY
VALUES(CATEGORY_NO_SEQ.NEXTVAL, 3,0,'패딩');
INSERT INTO CATEGORY
VALUES(CATEGORY_NO_SEQ.NEXTVAL, 4, 0, '무스탕');
INSERT INTO CATEGORY(CATEGORY_NO,CATE_NO,CATE_TITLE)
VALUES(CATEGORY_NO_SEQ.NEXTVAL, 1,'상의');
INSERT INTO CATEGORY
VALUES(CATEGORY_NO_SEQ.NEXTVAL, 0,1,'티셔츠');
INSERT INTO CATEGORY
VALUES(CATEGORY_NO_SEQ.NEXTVAL, 1,1,'블라우스/셔츠');
INSERT INTO CATEGORY
VALUES(CATEGORY_NO_SEQ.NEXTVAL, 2,1,'니트');

select * from category;
select *
from category
where  parent_no IS NULL
AND CATE_NO = 1;


