DROP TABLE CATEGORY;
DROP SEQUENCE CATEGORY_NO_SEQ;


CREATE SEQUENCE CATEGORY_NO_SEQ;


CREATE TABLE CATEGORY(
	CATEGORY_NO NUNMBER(20) PRIMARY KEY,
	CATE01 NUMBER(2) NOT NULL,  --0아우터,1상의,2하의,3악세사리
	CATE02 NUMBER(2) NOT NULL,  --0,1,2,3,4,5
	CATE01_NAME VARCHAR2(20) NOT NULL,
	CATE02_NAME VARCHAR2(20) NOT NULL,
);

INSERT INTO CATEGORY
VALUES(CATEGORY_NO_SEQ.NEXTVAL, 0,0,'아우터','가디건');
INSERT INTO CATEGORY
VALUES(CATEGORY_NO_SEQ.NEXTVAL, 0,1,'아우터','자켓/점퍼');
INSERT INTO CATEGORY
VALUES(CATEGORY_NO_SEQ.NEXTVAL, 0,2,'아우터','코트');
INSERT INTO CATEGORY
VALUES(CATEGORY_NO_SEQ.NEXTVAL, 0,3,'아우터','패딩');
INSERT INTO CATEGORY
VALUES(CATEGORY_NO_SEQ.NEXTVAL, 0,4,'아우터','무스탕');
INSERT INTO CATEGORY
VALUES(CATEGORY_NO_SEQ.NEXTVAL, 1,0,'아우터','티셔츠');
INSERT INTO CATEGORY
VALUES(CATEGORY_NO_SEQ.NEXTVAL, 1,1,'아우터','블라우스/셔츠');
INSERT INTO CATEGORY
VALUES(CATEGORY_NO_SEQ.NEXTVAL, 1,2,'아우터','니트');
INSERT INTO CATEGORY
VALUES(CATEGORY_NO_SEQ.NEXTVAL, 1,3,'아우터','맨투맨/후드');





