DROP TABLE CATEGORY;
DROP SEQUENCE CATEGORY_NO_SEQ;


CREATE SEQUENCE CATEGORY_NO_SEQ;


CREATE TABLE CATEGORY(
	CATEGORY_NO NUMBER(2) PRIMARY KEY,
	CATE_NO NUMBER(2) NOT NULL,  
	PARENT_NO NUMBER(2),  --0아우터,1상의,2하의,3악세사리, parent_no가 없으면 null
	CATE_TITLE VARCHAR2(20) NOT NULL
);

SELECT * FROM CATEGORY;
INSERT INTO CATEGORY
VALUES(CATEGORY_NO_SEQ.NEXTVAL, 0 , NULL,'아우터');
INSERT INTO CATEGORY
VALUES(CATEGORY_NO_SEQ.NEXTVAL, 0, 0,'가디건');
INSERT INTO CATEGORY
VALUES(CATEGORY_NO_SEQ.NEXTVAL, 1,0,'자켓/점퍼');
INSERT INTO CATEGORY
VALUES(CATEGORY_NO_SEQ.NEXTVAL, )

INSERT INTO CATEGORY
VALUES(CATEGORY_NO_SEQ.NEXTVAL, 0,2,'아우터','코트');
INSERT INTO CATEGORY
VALUES(CATEGORY_NO_SEQ.NEXTVAL, 0,3,'아우터','패딩');
INSERT INTO CATEGORY
VALUES(CATEGORY_NO_SEQ.NEXTVAL, 0,4,'아우터','무스탕');
INSERT INTO CATEGORY
VALUES(CATEGORY_NO_SEQ.NEXTVAL, 1,0,'아우터','티셔츠');
INSERT INTO CATEGORY
VALUES(CATEGORY_NO_SEQ.NEXTVAL, 1,1,'아우터','블라우스/셔츠');
INSERT INTO CATEGORY
VALUES(CATEGORY_NO_SEQ.NEXTVAL, 1,2,'아우터','니트');
INSERT INTO CATEGORY
VALUES(CATEGORY_NO_SEQ.NEXTVAL, 1,3,'아우터','맨투맨/후드');





