DROP TABLE ITEM;
DROP SEQUENCE ITEM_NO_SEQ;

CREATE SEQUENCE ITEM_NO_SEQ;

--상품
CREATE TABLE ITEM(
	ITEM_NO NUMBER(20) PRIMARY KEY,
	ITEM_NAME VARCHAR2(500) NOT NULL,
	ITEM_PRICE VARCHAR2(20) NOT NULL,
	ITEM_PHOTO VARCHAR2(1000) NOT NULL
);


