DROP TABLE LIKY;
DROP SEQUENCE LIKE_NO_SEQ;

CREATE SEQUENCE LIKE_NO_SEQ;

--좋아요
CREATE TABLE LIKY(
	LIKE_NO NUMBER(20) PRIMARY KEY,
	ITEM_NO NUMBER(20) NOT NULL,
	USER_NO NUMBER(20) NOT NULL,
	CONSTRAINT ITEM_NO_FK FOREIGN KEY (ITEM_NO) REFERENCES ITEM(ITEM_NO),
	CONSTRAINT USER_NO_FK FOREIGN KEY (USER_NO) REFERENCES USER_INFO(USER_NO)
);


