SELECT OBJECT_NAME, OBJECT_TYPE
FROM USER_OBJECTS;

--회원, 상품, 좋아요

DROP TABLE USER;
DROP SEQUENCE USER_SEQ;

CREATE SEQUENCE USER_SEQ;
CREATE TABLE USER_INFO(
	USER_NO NUMBER(20),
	USER_ID VARCHAR2(20) NOT NULL,
	USER_PW VARCHAR2(1000) NOT NULL,
	USER_NAME VARCHAR2(20) NOT NULL,
	USER_EMAIL VARCHAR2(500) NOT NULL,
	USER_ROLE VARCHAR2(20) NOT NULL,
	USER_PHONE VARCHAR2(500) NOT NULL,
	USER_ADDRESS VARCHAR2(500) NOT NULL,
	USER_REGDATE DATE NOT NULL,
	CONSTRAINT USERNO PRIMARY KEY (USER_NO),
	CONSTRAINT USERROLE CHECK (USER_ROLE IN ('USER', 'ADMIN'))
);

SELECT * FROM USER_INFO;


DROP TABLE ITEM;
DROP SEQUENCE ITEM_NO_SEQ;

CREATE SEQUENCE ITEM_NO_SEQ;
CREATE TABLE ITEM(
	ITEM_NO NUMBER(20) PRIMARY KEY,
	ITEM_NAME VARCHAR2(500) NOT NULL,
	ITEM_PRICE VARCHAR2(20) NOT NULL,
	ITEM_PHOTO VARCHAR2(1000) NOT NULL
);

DROP TABLE LIKY;
DROP SEQUENCE LIKE_NO_SEQ;

CREATE SEQUENCE LIKE_NO_SEQ;
CREATE TABLE LIKY(
	LIKE_NO NUMBER(20) PRIMARY KEY,
	ITEM_NO NUMBER(20) NOT NULL,
	USER_NO NUMBER(20) NOT NULL,
	CONSTRAINT ITEM_NO_FK FOREIGN KEY (ITEM_NO) REFERENCES ITEM(ITEM_NO),
	CONSTRAINT USER_NO_FK FOREIGN KEY (USER_NO) REFERENCES USER_INFO(USER_NO)
);

