DROP TABLE NOTICE;
DROP SEQUENCE NOTICE_NO_SEQ;

CREATE SEQUENCE NOTICE_NO_SEQ;

CREATE TABLE NOTICE(
	NOTICE_NO NUMBER(20) PRIMARY KEY,
	NOTICE_TITLE VARCHAR2(100) NOT NULL,
	NOTICE_WRITER VARCHAR2(20) NOT NULL,
	NOTICE_CONTENT VARCHAR2(2000) NOT NULL,
	NOTICE_VIEWER NUMBER(20) NOT NULL,
	NOTICE_REGDATE DATE NOT NULL
);

INSERT INTO NOTICE
VALUES(NOTICE_NO_SEQ.NEXTVAL, '배송 전 취소/변경 안내','담당자',
	'배송 전 수령자 벙보 변경 또는 주문상품의 취소/변경을 원하시는 경우 배송업무 시작 전인 10:00까지 Q&A 게시판 [배송 전 취소/변경 문의] 카테고리로 요청사항을 남겨주셔야 처리 가능한 점 참고 부탁드립니다.',
	0,SYSDATE);
	
SELECT * FROM NOTICE order by notice_no desc;

SELECT NOTICE_NO, NOTICE_TITLE, NOTICE_WRITER, NOTICE_CONTENT, 
			NOTICE_VIEWER, NOTICE_REGDATE
	FROM NOTICE
	ORDER BY NOTICE_NO DESC;