DROP TABLE QANDA;
DROP SEQUENCE QANDA_NO_SEQ;


CREATE SEQUENCE QANDA_NO_SEQ;

CREATE TABLE QANDA(
	QA_NO NUMBER(20) PRIMARY KEY,
	USER_NO NUMBER(20),
	QA_TITLE VARCHAR2(500) NOT NULL,
	QA_CONTENT VARCHAR2(2000) NOT NULL,
	QA_REGDATE DATE NOT NULL,
	CONSTRAINT USER_NO_FKFK FOREIGN KEY(USER_NO) REFERENCES USER_INFO(USER_NO)
)
select * from user_info

INSERT INTO QANDA
VALUES (QANDA_NO_SEQ.NEXTVAL, 22, '상품문의', '문의문의입니당',SYSDATE)
INSERT INTO QANDA
VALUES (QANDA_NO_SEQ.NEXTVAL, 22, '배송문의', '배송문의문의입니당',SYSDATE)
INSERT INTO QANDA
VALUES (QANDA_NO_SEQ.NEXTVAL, 41, '배송문의', '배송문의문의입니당',SYSDATE)

	SELECT qa.QA_NO, qa.QA_TITLE, qa.QA_CONTENT, qa.QA_REGDATE,
		ui.USER_NO, ui.USER_NAME, ui.USER_EMAIL
	FROM QANDA qa, USER_INFO ui
	WHERE qa.USER_NO = ui.USER_NO
	AND QA_NO = 3
	ORDER BY QA_NO DESC

	
	SELECT qa.QA_NO, qa.QA_TITLE, qa.QA_CONTENT, qa.QA_REGDATE,
		ui.USER_NO, ui.USER_NAME, ui.USER_EMAIL
	FROM QANDA qa, USER_INFO ui
	WHERE qa.USER_NO = ui.USER_NO
	ORDER BY QA_NO DESC